### ISSUE TITLE
Please check

### ISSUE THREAD

**Issue by BellemareMederic** [shell-c0d3/wireless#1]
Chec your needed packet to run your application Air-crack and auto installe it !

<pre>
DEPS="Air-crack ETC ETC"
for i in $DEPS ; do
    dpkg-query -W -f='${Package}\n' | grep ^$i$ > /dev/null
    if [ $? != 0 ] ; then
      echo "$i --> FAIL"
        read -p "do you want install ($i) or exit the script (y/n) :" choix
        if [ $choix = "y" ]; then
            echo "($i) Installing..."
            sudo apt-get install $i -y > /dev/null
            else
            exit
        fi
            else
            echo "$i --> OK"
        fi
    done </pre>

**Comment by Jeff-Blane** [comment]
Thanks so much for the tip :)
I added the functionality last night as well as menu selections for each section.

**Comment by BellemareMederic** [comment]
No problem ! Have nice holiday and never stop programing :)
